### ISSUE TITLE
Rotation without click but mousehover

### ISSUE THREAD

**Issue by markosansa** [heartcode/360-Image-Slider#4]
Hello! Very good code!!!!!
Only a question! Is it possible to active the images movements without mouse click but with mouse hover? 

Thank you so much! 

Mark

**Comment by heartcode** [comment]
Hi, sure just swap the `mousedown`/`mouseup` in the code to `mouseover`/`mouseout` or `mouseenter`/`mouseleave`, that should do the 'quick and dirty' trick. For more info on the jQuery mouse events, please visit: [http://api.jquery.com/category/events/mouse-events/](http://api.jquery.com/category/events/mouse-events/). Good luck!

**Comment by markosansa** [comment]
Oook! Thank you so much heartcode! 

Mark
